---
- hosts: webservers
  become: yes
  tasks:
    - name: Copy the LAMP setup script to the remote server
      copy:
        src: /home/vagrant/cloud_project/deploy_new.sh
        dest: /home/vagrant/deploy_new.sh
        mode: '0755'

   # - name: Execute the LAMP setup script
    #  command: /home/vagrant/deploy_new.sh
     # register: setup_output

    - name: Ensure the Apache service is running
      service:
        name: apache2
        state: started

    - name: Ensure the MySQL service is running
      service:
        name: mysql
        state: started

    - name: Create a cron job to check server uptime
      cron:
        name: "uptime_check"
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/uptime.log"
