---
- hosts: webservers
  become: yes
  tasks:
    - name: Copy the LAMP setup script to the remote server
      copy:
        src: /home/vagrant/cloud_project/deploy_new.sh
        dest: /home/vagrant/deploy_new.sh
        mode: '0755'

<<<<<<< HEAD
   # - name: Execute the LAMP setup script
    #  command: /home/vagrant/deploy_new.sh
     # register: setup_output
=======
    - name: Execute the LAMP setup script
      command: /home/vagrant/deploy_new.sh
      register: setup_output
>>>>>>> 78709c15d5ad0f69229adf88ba671e8596e7a6c4

    - name: Ensure the Apache service is running
      service:
        name: apache2
        state: started

    - name: Ensure the MySQL service is running
      service:
        name: mysql
        state: started

    - name: Create a cron job to check server uptime
      cron:
        name: "uptime_check"
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/uptime.log"
